### PR TITLE
Upgrade to paraboiled 2.1.0

### PR DESCRIPTION
**Pull request by crakjie**

### CODE REVIEW

**Comment by theon** [comment]
Thanks!

**Comment by crakjie** [comment]
Would you do a vertion or a snapshot from this?

**Comment by theon** [comment]
@crakjie sorry for the delay. Published now as `0.4.8`

**Comment by crakjie** [comment]
Thank you !
I don't know why I was unable to use the github version. Each time I used this in sbt dependency (with dependsOn ) sbt pull the 0.4.7 jar from maven.

**Pull request merged**
