### PR TITLE
Fixes MatrixParam parsing for issue #102

### PR DESCRIPTION
**Pull request by fsaintjacques**

### CODE REVIEW

**Comment by fsaintjacques** [comment]
@theon would it be possible to release a fix for this in the maven repo (for both scala 2.10/2.11) ?

**Comment by theon** [comment]
Sorry for the delay! This one slipped through the net. I will get a release out today.

**Comment by theon** [comment]
and thanks for the contribution :)

**Comment by theon** [comment]
I just published a `0.4.9` release which should have this included.

**Comment by fsaintjacques** [comment]
Note that my solution is not 100% clean, there might be a better way to shape the parsing.

**Pull request merged**
