### PR TITLE
Fix for issue #85

### PR DESCRIPTION
**Pull request by sauravshah**

### CODE REVIEW

**Comment by theon** [comment]
Thanks!

**Comment by sauravshah** [comment]
Thanks @theon ! Can you please upload a new version to maven?

**Comment by theon** [comment]
@sauravshah `0.4.5` should be in the sonatype maven repo now and in maven central within a couple hours.

Thanks again for the contribution!

**Comment by sauravshah** [comment]
Hi @theon ,

The version should be 0.4.6? I was already using 0.4.5 earlier.

**Comment by theon** [comment]
Odd. I'm not sure where you got `0.4.5` from before yesterday. It only hit maven central yesterday:

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.netaporter%22%20AND%20a%3A%22scala-uri_2.11%22

I had a look in the commit history and couldn't find a `0.4.5` there anywhere.

**Comment by theon** [comment]
Although the date on that link says "Updated"... As a test I just tried re-publishing `0.4.5` and was surprised that it didn't stop me. Maybe I have some changes that bumped the version to `0.4.5` on my work laptop and I forgot to push them. Sorry about that!

I have now published a `0.4.6`.

**Pull request merged**
